name: ClearVision
author: Zerthox
description: ClearVision is an automatically updating, easily customizable theme for Discord.

exclude:
    - README.md
    - LICENSE
    - Gemfile

sass:
    sass_dir: /
    style: compressed